<?php if (count($this->getProducts())): ?>
    <?php $_params = $this->escapeHtml(json_encode(array('form_key' => $this->getFormKey()))) ?>
    <div class="widget widget-recommendations-products">
        <div class="widget-title">
            <h2 style="display: inline-block; margin-right: 10px;"><?= $this->__('Recommended Items') ?></h2>
            <?= $this->getLayout()
                ->createBlock('b24chat_integration/interactive')
                ->setScenarioId(547) // TODO: брать id из настроек
                ->toHtml() ?>
        </div>
        <div class="widget-products">
            <?= $this->getPagerHtml() ?>
            <?php $_columnCount = $this->getColumnCount(); ?>
            <?php $i = 0;
            foreach ($this->getProducts() as $_product): ?>
                <?php if ($i++ % $_columnCount == 0): ?>
                    <ul class="products-grid">
                <?php endif ?>
                <li class="item<?php if (($i - 1) % $_columnCount == 0): ?> first<?php elseif ($i % $_columnCount == 0): ?> last<?php endif; ?>">
                    <a href="<?= $_product->getProductUrl() ?>"
                       title="<?= $this->stripTags($_product->getName(), null, true) ?>"
                       class="product-image"><img
                                src="<?= $this->helper('catalog/image')->init($_product, 'small_image')->resize(85) ?>"
                                width="85" height="85"
                                alt="<?= $this->stripTags($_product->getName(), null, true) ?>"/></a>
                    <h3 class="product-name"><a href="<?= $_product->getProductUrl() ?>"
                                                title="<?= $this->stripTags($_product->getName(), null, true) ?>)"><?= $this->helper('catalog/output')->productAttribute($_product, $_product->getName(), 'name') ?></a>
                    </h3>
                    <?= $this->getReviewsSummaryHtml($_product, 'short') ?>
                    <?= $this->getLayout()->createBlock('catalog/product_price')
                        ->setTemplate('catalog/product/price.phtml')
                        ->setProduct($_product)
                        ->setDisplayMinimalPrice(true)
                        ->setIdSuffix($idSuffix='-widget-recommendations-grid')
                        ->toHtml(); ?>
                    <div class="actions">
                        <?php if ($_product->isSaleable()): ?>
                            <button type="button"
                                    title="<?= Mage::helper('core')->quoteEscape($this->__('Add to Cart')) ?>"
                                    class="button btn-cart"
                                    onclick="customFormSubmit(
                                            '<?= $this->getAddToCartUrlCustom($_product, array(), false) ?>',
                                            '<?= $_params ?>',
                                            'post')">
                                <span><span><?= $this->__('Add to Cart') ?></span></span>
                            </button>
                        <?php else: ?>
                            <p class="availability out-of-stock"><span><?= $this->__('Out of stock') ?></span>
                            </p>
                        <?php endif; ?>
                        <ul class="add-to-links">
                            <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                <li>
                                    <a href="#"
                                       class="link-wishlist"
                                       onclick="customFormSubmit(
                                               '<?= $this->getAddToWishlistUrlCustom($_product, false) ?>',
                                               '<?= $_params ?>',
                                               'post')">
                                        <?= $this->__('Add to Wishlist') ?>
                                    </a>
                                </li>
                            <?php endif; ?>
                            <?php if ($_compareUrl = $this->getAddToCompareUrlCustom($_product, false)) : ?>
                                <li>
                                    <span class="separator">|</span>
                                    <a href="#"
                                       class="link-compare"
                                       onclick="customFormSubmit(
                                               '<?= $_compareUrl ?>',
                                               '<?= $_params ?>',
                                               'post')">
                                        <?= $this->__('Add to Compare') ?>
                                    </a>
                                </li>
                            <?php endif; ?>
                        </ul>
                    </div>
                </li>
                <?php if ($i % $_columnCount == 0 || $i == count($this->getProducts())): ?>
                    </ul>
                <?php endif ?>
            <?php endforeach; ?>
        </div>
    </div>
<?php endif; ?>
